version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      # 06:30 UTC = 08:30 Heidelberg
      time: '06:30'
      open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      # 06:30 UTC = 08:30 Heidelberg
      time: '06:30'
      open-pull-requests-limit: 10
