name: 'Tangro Audit'
description: 'Run npm audit'
author: 'tangro'
inputs:
  post-comment:
    description: 'Set to true to post a comment after the audit result has been collected. Default false'
    default: false
  workingDirectory:
    description: 'Set the working directory'
    default: ''
  actionName:
    description: 'Set different action (and output directory) name. This is needed if the action is used more than once in a repo.'
    default: 'audit'
  production:
    description: 'Set to true to not run on devDependencies.'
    default: false    
    
outputs:
  vulnerabilities:
    description: '{ info: number, low: number, moderate: number, high: number, critical: number }'

runs:
  using: 'node12'
  main: 'dist/index.js'
