name: 'Tangro Audit'
description: 'Run npm audit'
author: 'tangro'
inputs:
  post-comment:
    description: 'Set to true to post a comment after the audit result has been collected. Default false'
    default: false
  workingDirectory:
    description: 'Set the working directory'
    default: ''
  actionName:
    description: 'Set different action name. This is needet if the action is uset more than one in a repo.'
    default: 'audit'
runs:
  using: 'node12'
  main: 'dist/index.js'
